### ISSUE TITLE
On compile asking for fwatch.lib

### ISSUE THREAD

**Issue by shivergard** [Faguss/fwatch#1]
--------------------Configuration: TestLauncher - Win32 Release--------------------
Build : warning : failed to (or don't know how to) build 'C:\Users\Administrator\Desktop\fwatch-master\fwatch.lib'
Linking...
LINK : fatal error LNK1181: cannot open input file "..\fwatch.lib"
Error executing link.exe.

fwatch.exe - 1 error(s), 1 warning(s)

if removed from compiling

`--------------------Configuration: TestLauncher - Win32 Release--------------------
Linking...
TestLauncher.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl RemoveHook(void)" (__imp_?RemoveHook@@YAXXZ)
TestLauncher.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl InstallHook(void)" (__imp_?InstallHook@@YAXXZ)
..\fwatch.exe : fatal error LNK1120: 2 unresolved externals
Error executing link.exe.

fwatch.exe - 3 error(s), 0 warning(s)`

**Comment by Faguss** [comment]
First you need to compile fwatch.dll (TestDLL\TestDLL.dsw) and that will generate fwatch.lib file.
